name: Community
description: ${project.description}
main: ${project.mainClass}
version: ${project.version} (git-${git.commit.id.abbrev})
website: ${project.url}
author: ${project.author}
softdepend: [PGM]
