name: Community
description: ${description}
api-version: ${apiVersion}
main: ${mainClass}
version: ${version} (git-${commitHash})
website: ${url}
author: ${author}
softdepend: [Database, PGM, Environment, packetevents, ViaVersion]
